import type { editor } from "monaco-editor";
import type { Theme } from "./theme";

export const MONACO_THEMES: Record<Theme, editor.IStandaloneThemeData> = {
  green: {
    base: "vs-dark",
    inherit: true,
    rules: [],
    colors: {
      "editor.background": "#0a1210",
      "editorGutter.background": "#0a1210",
      "editorLineNumber.foreground": "#496057",
      "editorLineNumber.activeForeground": "#9bb5aa",
      "diffEditor.insertedTextBackground": "#1f7a5242",
      "diffEditor.removedTextBackground": "#b64b5542",
      "diffEditor.insertedLineBackground": "#123b2b88",
      "diffEditor.removedLineBackground": "#3d202588",
      "diffEditor.diagonalFill": "#18231f",
      "editorOverviewRuler.addedForeground": "#67dba0",
      "editorOverviewRuler.deletedForeground": "#f2777f",
      "scrollbarSlider.background": "#66807433",
      "scrollbarSlider.hoverBackground": "#78998a66",
    },
  },
  dark: {
    base: "vs-dark",
    inherit: true,
    rules: [],
    colors: {
      "editor.background": "#171717",
      "editorGutter.background": "#171717",
      "editorLineNumber.foreground": "#737373",
      "editorLineNumber.activeForeground": "#d4d4d4",
      "diffEditor.insertedTextBackground": "#2f7d4d55",
      "diffEditor.removedTextBackground": "#a94c5555",
      "diffEditor.insertedLineBackground": "#173d2788",
      "diffEditor.removedLineBackground": "#43232988",
      "diffEditor.diagonalFill": "#262626",
      "editorOverviewRuler.addedForeground": "#57c785",
      "editorOverviewRuler.deletedForeground": "#ef7a82",
      "scrollbarSlider.background": "#77777733",
      "scrollbarSlider.hoverBackground": "#99999966",
    },
  },
  light: {
    base: "vs",
    inherit: true,
    rules: [],
    colors: {
      "editor.background": "#ffffff",
      "editorGutter.background": "#ffffff",
      "editorLineNumber.foreground": "#8b8b8b",
      "editorLineNumber.activeForeground": "#333333",
      "diffEditor.insertedTextBackground": "#60b8784a",
      "diffEditor.removedTextBackground": "#e06c754a",
      "diffEditor.insertedLineBackground": "#dff4e688",
      "diffEditor.removedLineBackground": "#f9dfe288",
      "diffEditor.diagonalFill": "#eeeeee",
      "editorOverviewRuler.addedForeground": "#258a52",
      "editorOverviewRuler.deletedForeground": "#c44550",
      "scrollbarSlider.background": "#77777733",
      "scrollbarSlider.hoverBackground": "#66666655",
    },
  },
  glass: {
    base: "vs-dark",
    inherit: true,
    rules: [],
    colors: {
      "editor.background": "#0b1622",
      "editorGutter.background": "#0b1622",
      "editorLineNumber.foreground": "#557087",
      "editorLineNumber.activeForeground": "#c7dceb",
      "diffEditor.insertedTextBackground": "#2b9b7350",
      "diffEditor.removedTextBackground": "#c35f6c50",
      "diffEditor.insertedLineBackground": "#123b3488",
      "diffEditor.removedLineBackground": "#42263388",
      "diffEditor.diagonalFill": "#152436",
      "editorOverviewRuler.addedForeground": "#72dfbd",
      "editorOverviewRuler.deletedForeground": "#f28691",
      "scrollbarSlider.background": "#8fb3ca2b",
      "scrollbarSlider.hoverBackground": "#a8c8db55",
    },
  },
  neumorphic: {
    base: "vs-dark",
    inherit: true,
    rules: [],
    colors: {
      "editor.background": "#101922",
      "editorGutter.background": "#101922",
      "editorLineNumber.foreground": "#566b79",
      "editorLineNumber.activeForeground": "#c8d8df",
      "diffEditor.insertedTextBackground": "#297a5e55",
      "diffEditor.removedTextBackground": "#a84d5a55",
      "diffEditor.insertedLineBackground": "#15372e88",
      "diffEditor.removedLineBackground": "#3b252d88",
      "diffEditor.diagonalFill": "#192732",
      "editorOverviewRuler.addedForeground": "#6bd8b6",
      "editorOverviewRuler.deletedForeground": "#eb808b",
      "scrollbarSlider.background": "#6c879833",
      "scrollbarSlider.hoverBackground": "#87a5b766",
    },
  },
};
